Input argument validation layer
KhronosGroup/OpenCL-Layers pull request #11
Opened 2022-06-16 15:25 UTC by MathiasMagnus

# Input Parameter Validation Layer

_(This PR is based on top of #7 that's why the changeset is currently large, but folders cleanly separate changes.)_

The layer detects and reports (almost) all errors on input parameters and log, for each OpenCL API entry point of base OpenCL 3.0 specification (without extensions), (almost) all error conditions as defined in the API documentation that derive from the parameters used to call the function, and optionally returns the error. All the parameter tests are described in XML with the help of schema below.

The layer is stateless as of now and rely on querying properties of OpenCL objects from the underlying OpenCL implementation (or layer). The sequence of parameter validation tests is structured in such a way that querying should proceed only on the existing objects with guaranteed type and properties.

> Note: the stateless nature is a simplification only. Keeping track of object relationships is very much possible and the bulk of it has already been done in the object lifetime layer. Reusing that logic can be added later, but it does requre mild refactoring. Doing so would still require some queries be done on the fly or during init, because some validations depend on runtime properties, such as device supporting images or not, as these alter the validity of input args to some functions.

## Source files

The layer depends on an XML library of our choice ([RapidXML](http://rapidxml.sourceforge.net/)) which is used to compile `param-verification/parser.cpp`, which results in a binary that processes `param-verification/cl-avl.xml`, a copy of upstream `cl.xml` from OpenCL-Docs. This binary generates the rest of the source file `res.cpp` which together with the auxiliary:
- `param_verification.hpp`
- `object_is_valid.cpp`
- `list_violation.cpp`
- `struct_violation.cpp`
helper files comprise the bulk of the validation logic. The initialization of the layer is in the file `param-verification/param_verification.cpp`.

CMake build automation properly takes care of both fetching RapidXML (if not found) and also orders the building of the code generator with the rest of the build.

## XML schema
Starting from [cl.xml](https://github.com/KhronosGroup/OpenCL-Docs/blob/main/xml/cl.xml) of OpenCL, we use the definitions of functions of the type

```xml
        <command suffix="CL_API_SUFFIX__VERSION_1_0">
            <proto><type>cl_mem</type>                                  <name>clCreateBuffer</name></proto>
            <param><type>cl_context</type>                              <name>context</name></param>
            <param><type>cl_mem_flags</type>                            <name>flags</name></param>
            <param><type>size_t</type>                                  <name>size</name></param>
            <param><type>void</type>*                                   <name>host_ptr</name></param>
            <param><type>cl_int</type>*                                 <name>errcode_ret</name></param>
```

and extend them with conditions for violations of argument validity with corresponding returned errors. Conditions follow the the parameters and are enclosed by `<conditions>` tag. Each condition consists of two tags: `<if>` and `<then>`. The former represents arguments invalidation condition itself, the latter provides outcomes, i.e. specific function returns.

`<if>` tag consists of conditions on parameters that invalidate function in some way. Tags of `<not>`, `<and>`, `<or>` can be used with usual meaning to combine simpler conditions, `<and>` and `<or>` can include two or more conditions inside. Basic conditions are:
* `<eq>` - equal
* `<neq>` - not equal
* `<gt>` - greater
* `<ls>` - less
* `<array_len_ls>` - length of array provided by pointer xxx is less then yyy (dummy function as of yet, always provides false)
* `<bit_and>` - gives true if bitwise and operation between xxx and yyy returns non-zero
* `<mutex_violation>` - gives true if two or more of conditions inside are true
* `<from>` - gives true if version of OpenCL is greater or equal to xxx
* `<enum_violation name="xxx"/>` - gives true if the value of parameter xxx is outside of valid for its type 
* `<bitfield_violation name="xxx"/>` - gives true if the value of parameter xxx is outside of valid for its type (0 is treated as valid)
* `<list_violation name="xxx" param="yyy, zzz"/>` - gives true if the structure of list xxx is invalid for its type taking into account also the values of yyy, zzz, etc. (param property is optional, test functions should be written manually for the layer)
* `<struct_violation name="xxx" param="yyy, zzz"/>` - gives true if the structure of xxx is invalid taking into account also the values of yyy, zzz, etc. (param property is optional, test functions should be written manually)
* `<any_nullptr array="xxx" elements="yyy"/>` - gives true if any of the pointers in array xxx of yyy elements is NULL
* `<any_zero array="xxx" elements="yyy"/>` - gives true if any of the values in array xxx of yyy elements is 0
* `<object_is_invalid name="xxx"/>` - gives true if the object is invalid
* `<object_is_invalid name="xxx" type="yyy"/>` - gives true if the object is invalid or is not of the given type
* `<any_invalid array="xxx" elements="yyy"/>` - gives true if any of the objects in array xxx of yyy elements is invalid
* `<any_non_null_invalid array="xxx" elements="yyy"/>` - gives true if any of the objects in array xxx of yyy elements besides its NULL elements is invalid
* `<any_not_available array="devices" elements="yyy"/>` - gives true if any of yyy devices is unavailable
* `<object_not_in object="xxx" in="yyy"/>` - gives true if object xxx does not belong to object yyy (e.g. queue is not on device, contexts of the xxx and yyy are not the same, etc.)
* `<any_object_not_in array="xxx" elements="yyy" in="zzz"/>` - gives true if any object in array xxx of yyy elements does not belong to object zzz (e.g. contexts of the events xxx and command queue zzz are not the same, etc.)
* `<for_all in="xxx" query="yyy">` - gives true if all the evaluations of expression inside the tag for all devices associated with xxx (e.g. all devices in context, associated with kernel, etc.) give true, expression can use `<name>query</name>` as value of queried property yyy for every device 
* `<for_any in="context" query="xxx">` - gives true if any of the evaluations of expression inside the tag for all devices associated with xxx (e.g. all devices in context, associated with kernel, etc.) give true, expression can use `<name>query</name>` as value of queried property yyy for every device 
* `<not_aligned pointer="xxx" align="yyy"/>` - gives true if pointer xxx is not aligned to yyy bytes
* `<check_copy_overlap param="xxx"/>` - gives true is provided parameters xxx ensure overlap of regions to be read from and written to

Parameters of the conditions can be of types: `<name>`, `<literal>`, `<literal_list>`, `<sizeof>`, `<mult>`, `<mod>`, `<max>`, `<query>`. 
* `<name>` gives the value of the corresponding function parameter.
* `<literal>` gives literal constant.
* `<literal_list>` gives literal constant from the list connected to the type of parameter, corresponding to the value of parameter inside the tag.
* `<sizeof>` gives size of type.
* `<mult>` provides multiplication of its parameters.
* `<add>` provides addition of its parameters.
* `<mod>` gives xxx modulo yyy.
* `<max>` gives maximum of its two parameters.
* `<query object="xxx" property="yyy"/>` gives the value of property yyy of object xxx (or of the associated object, i.e. you can query property of device associated with command queue xxx), if it is a variable-size array property, only the first array element is returned

Example (continued):
```xml
<if>
  <for_all in="context" query="CL_DEVICE_MAX_MEM_ALLOC_SIZE">
    <gt>
      <name>size</name> <name>query</name>
    </gt>
  </for_all>
</if>
```

`<then>` tag consists of blocks defining returned parameters for the specific case defined  [...]

2022-06-23 23:11 UTC, Kerilk commented
@MathiasMagnus kind reminder to rebase this one so comparison is a tad easier.

2022-06-28 21:07 UTC, Kerilk requested changes

2022-06-28 21:07 UTC, Kerilk commented on object-lifetime/object_lifetime_test_icd.hpp
> -#include <mutex>        // std::mutex
Is this removal intended?

2022-06-28 21:07 UTC, Kerilk commented on object-lifetime/object_lifetime_test_icd.cpp
> -  dispatch->clCreateKernelsInProgram = clCreateKernelsInProgram_wrap;
This seems to remove the most recent additions from the lifetime counting layer.

2022-06-28 21:07 UTC, Kerilk commented on object-lifetime/object_lifetime_test_icd.cpp
> -  , _global_mutex{}
Is this removal intended?

2022-06-28 21:07 UTC, Kerilk commented on object-lifetime/object_lifetime_test_icd.cpp
> -
This seems to remove the most recent additions from the lifetime counting layer.

2022-06-28 21:07 UTC, Kerilk commented on object-lifetime/object_lifetime.cpp
> + if (devices && result == CL_SUCCESS && actual_num_entries > 0)
This seems to remove the most recent additions from the lifetime counting layer.

2022-06-28 21:07 UTC, Kerilk commented on cmake/run_and_compare.cmake
> +        message(FATAL_ERROR "Mismatch in output: ${OUTPUT_FILE}, expected: ${EXPECTED_FILE}")
This seems to remove the most recent additions from the lifetime counting layer.

2022-06-28 21:15 UTC, Kerilk commented
This first round of comments addresses the rebase which seems problematic:
https://github.com/KhronosGroup/OpenCL-Layers/pull/7/commits/5958fec53573da41f43897c5cf27bd9b44401350 https://github.com/KhronosGroup/OpenCL-Layers/pull/7/commits/78f40fceb59f8810cef3d47cd7b93b1978e5bede https://github.com/KhronosGroup/OpenCL-Layers/pull/7/commits/8bc5c9b81a45016d04e486d430508ae0f18e4991 https://github.com/KhronosGroup/OpenCL-Layers/pull/7/commits/cc32130f90bf985f43898b4fe1034b1c5fa16f5b
seem to have been partially or totally lost after the rebase. I tried to pinpoint all the problematic sections I could find, but some changes may have been intentional, so a thorough verification is required. Sorry about that.

2022-07-06 21:04 UTC, MathiasMagnus commented
@Kerilk Yeah, apologies for that. I added those missing commits on top plus one correcting the namespaces of the test helpers.

2022-07-06 21:08 UTC, MathiasMagnus commented on cmake/run_and_compare.cmake
> +        message(FATAL_ERROR "Mismatch in output: ${OUTPUT_FILE}, expected: ${EXPECTED_FILE}")
In the now properly rebased version this seems to be solved.

2022-07-06 22:16 UTC, Kerilk commented
One small comment:
 * For Infos that return a variable amount of data, shouldn't we be querying the underlying driver for the size of the data?
Example with `clGetDeviceInfo` and `CL_DEVICE_NAME` for now the layer is comparing the size of the provided buffer with `sizeof(char[1])`. To be valid, shouldn't the buffer be of at least the size the underlying implementation requested, obtained through the `param_value_size_ret`? This problem is different than the one mentioned in https://github.com/KhronosGroup/OpenCL-Layers/issues/12 and does not require as much tooling.

2022-07-06 22:36 UTC, Kerilk commented
Aside from the small comment above, things look good from here.

2022-07-26 16:08 UTC, Kerilk approved these changes

2022-07-26 20:37 UTC, merged