Settings location
KhronosGroup/OpenCL-Layers pull request #6
Opened 2022-04-12 15:35 UTC by MathiasMagnus

This is an implementation of layer settings file location inside the common layer utility library.

2022-04-12 15:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/OpenCL-Layers?pullRequest=6) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/OpenCL-Layers?pullRequest=6) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: MathiasMagnus<br/>:x: Maetveis<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/OpenCL-Layers?pullRequest=6) it.</sub>

2022-05-03 16:58 UTC, Kerilk requested changes
Thanks for the great work, just minor comments and issues I could find.

2022-05-03 16:58 UTC, Kerilk commented on object-lifetime/object_lifetime.cpp
> +    CHECK_EXISTS_ERRC(OCL_IMAGE, image, errcode_ret, cl_mem);
Shouldn't it be a `CHECK_CREATION_ERRC`?

2022-05-03 16:58 UTC, Kerilk commented on utils/utils.cpp
> +#ifdef __linux__
I have two concerns here, which are not related to the quality of the code, but to the general configuration file behavior:
 - I realize we don't have system layers for now, but once we have, we may very well have a `cl_layer_settings.txt` somewhere in `/etc/OpenCL`, so we would need a mechanism to load this file first and then merge the user configuration into the existing dictionary. Do we want to merge/release a version of the utils without this system layer configuration active? I am not against merging it as is, I just want to make sure we're not creating a problem for ourselves later.
 - In an HPC context, unconditionally doing file system operations in home folders can result in the job hammering the network filesystem. As a safety I would add an environment variable preventing the automatic loading of any user configuration from the home folder. Using the `OPENCL_LAYERS_SETTINGS_PATH` should still work even with this safety activated.

2022-05-04 08:23 UTC, MathiasMagnus commented on object-lifetime/object_lifetime.cpp
> -#include <string_view>
The RFP specifically stated that layers be written in C++14. If that requirement is negotiable, we'll be happy to revert these changes.

2022-05-04 08:38 UTC, MathiasMagnus commented on object-lifetime/object_lifetime.cpp
> +    CHECK_EXISTS_ERRC(OCL_IMAGE, image, errcode_ret, cl_mem);
Indeed, that should be
```c++
if (image)
    CHECK_CREATION_ERRC(OCL_IMAGE, image, get_parent(image), errcode_ret, cl_mem);
return image;
```
While checking, found another occurence where we used duplicated logic instead of calling a function to check parent.

2022-05-04 08:51 UTC, MathiasMagnus commented on utils/utils.cpp
> +#ifdef __linux__
The OpenCL-Layers repo is still versioned as 0.1.
```cmake
project (OpenCL-Layers
    VERSION 0.1
    LANGUAGES C CXX
)
```
That should send a message that it isn't production ready yet, at least not to the levels of concerns you mention. Merging with a yet non-existing file, and in a multi-hundred node HPC system the effects of hammering network storage.

If you ask me, I'd be fine opening issues for these and defer implementing, but if we fear that we'll be breaking people's workflows, we could squeeze it in here. I personally would vote for deferring (and opening an issue). The workflows we'd break don't exist yet.

_(Note: having system layers would also alter how the registry is interrogated. In non-elevated processes, both `HKLM:\` and `HKCU:\` would need to be inspected and merged. Not a lot of people should be depending on user hive overriding the machine key hive.)_

2022-05-04 14:04 UTC, Kerilk commented on object-lifetime/object_lifetime.cpp
> -#include <string_view>
My lack of C++ knowledge shows, I am mostly a C guy. Let's keep it like that and I will try to come up with a way to avoid those allocations.

2022-05-04 14:11 UTC, Kerilk commented on utils/utils.cpp
> +#ifdef __linux__
Let's defer for now and open issues.

2022-05-04 14:16 UTC, Snektron commented on object-lifetime/object_lifetime.cpp
> -#include <string_view>
This could be implemented by using std::ostream::write to print instead of <<, and just writing `strlen(funcname) - 5` characeters. A wrapper type with an << overload can be used to make it look a bit nicer as well.

2022-05-04 14:21 UTC, Kerilk commented on object-lifetime/object_lifetime.cpp
> +    CHECK_EXISTS_ERRC(OCL_IMAGE, image, errcode_ret, cl_mem);
Nice catching the other one.

2022-05-06 08:59 UTC, MathiasMagnus commented on object-lifetime/object_lifetime.cpp
> -#include <string_view>
Instead of deferring, I went ahead and fixed the way @Snektron suggested. We both thought it's clean enough.

2022-05-06 09:01 UTC, MathiasMagnus commented on utils/utils.cpp
> +#ifdef __linux__
Issue #8 opened.

2022-05-06 09:07 UTC, MathiasMagnus commented
For the first time ever, MSVC's infamous `warning C4127: conditional expression is constant` proved useful and [caught a bug](https://github.com/KhronosGroup/OpenCL-Layers/pull/6/commits/cc30c4de7a739d70d87a9b96dd6a4e2fcd4baba9).

2022-05-06 15:40 UTC, Kerilk commented on object-lifetime/object_lifetime.cpp
> -#include <string_view>
Looks good, thanks.

2022-05-06 15:43 UTC, Kerilk approved these changes

2022-05-06 17:10 UTC, merged